// <auto-generated />
namespace ToDoApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Initcommit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initcommit));
        
        string IMigrationMetadata.Id
        {
            get { return "201408271056372_Init commit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
